/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Center: typeof import('./src/components/center.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FaMenXiJie: typeof import('./src/components/FaMenXiJie/index.vue')['default']
    KongTiao: typeof import('./src/components/kongTiao/index.vue')['default']
    NongDuXiJie: typeof import('./src/components/NongDuXiJie/index.vue')['default']
    Officereview: typeof import('./src/components/officereview.vue')['default']
    RenTiXiJie: typeof import('./src/components/RenTiXiJie/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ReIcon/src/Select.vue')['default']
    Tufour: typeof import('./src/components/tufour/index.vue')['default']
    Tuone: typeof import('./src/components/tuone/index.vue')['default']
    Tuthree: typeof import('./src/components/tuthree/index.vue')['default']
    Tutwo: typeof import('./src/components/tutwo/index.vue')['default']
    XiJie: typeof import('./src/components/XiJie/index.vue')['default']
    XinDianEchart: typeof import('./src/components/XinDianEchart/index.vue')['default']
    ZhongXinCeShuJuHuiZong: typeof import('./src/components/ZhongXinCeShuJuHuiZong/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
